<a href="https://colab.research.google.com/github/kamathkarthik95/GenerativeAI/blob/main/Vector_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Initial Setup: Installing a Key Library

This cell installs the `sentence-transformers` library, which is essential for our task. This library provides pre-trained models that can convert text into numerical vectors, known as **embeddings**. These embeddings capture the semantic meaning of sentences, allowing us to compare them mathematically.

In [ ]:
!pip install sentence-transformers

### Preparing the Data and Tools

In this cell, we perform two main actions:

1.  **Import Libraries**: We import `numpy` (as `np`) for numerical operations, especially useful when working with vectors and matrices, and `SentenceTransformer` from the `sentence_transformers` library, which is the core tool we'll use.
2.  **Define Sentences**: We create a Python list named `sentence` containing several strings. These are the sentences we want to convert into numerical representations (embeddings) to analyze their similarity.

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

sentence=["Machine learning is a subset of artificial intelligence",
"Deep learning uses nueral networks with many layers",
"natural language processing is popular for sentiment analysis and data science",
"azure provides cloud-based ai and ml services"]

### Generating Sentence Embeddings

Here, we take our sentences and transform them into **embeddings**:

1.  **Load Pre-trained Model**: `model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')` loads a pre-trained neural network model. This specific model (`all-MiniLM-L6-v2`) is chosen for its efficiency and good performance in generating sentence embeddings.
2.  **Encode Sentences**: `embeddings = model.encode(sentence)` is the crucial step where the model processes each sentence in our `sentence` list and converts it into a high-dimensional numerical vector. These vectors are designed so that sentences with similar meanings are closer together in the vector space.
3.  **Display Embeddings**: `print(embeddings)` shows the generated numerical vectors. Each row in the output corresponds to an embedding for one of our input sentences.

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings=model.encode(sentence)
print (embeddings)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[-0.04610743 -0.00426065  0.06983659 ...  0.05947231  0.08633482
  -0.0477733 ]
 [-0.0484728  -0.07698314  0.06780028 ...  0.01073241 -0.01566782
  -0.0291487 ]
 [-0.04240144 -0.01647179  0.05631926 ...  0.0577046   0.01285446
   0.02683141]
 [-0.05365124 -0.05941995  0.02611315 ... -0.03063848  0.07520911
  -0.07894178]]


### Understanding the Shape of Embeddings

`embeddings.shape` tells us the dimensions of our `embeddings` array. The output `(4, 384)` means:

*   `4`: We have 4 sentences.
*   `384`: Each sentence has been converted into a vector with 384 dimensions. This number represents the complexity of the semantic information captured by the model for each sentence.

In [ ]:
embeddings.shape

(4, 384)

### Inspecting a Single Embedding

`embeddings[1]` allows us to look at the numerical vector (embedding) for the second sentence in our `sentence` list (remember, Python uses 0-based indexing, so index 1 refers to the second item). This is just a demonstration to show the individual numerical values that make up one sentence's representation.

In [ ]:
embeddings[1]

array([-4.84727956e-02, -7.69831389e-02,  6.78002834e-02, -4.53375094e-02,
        3.33485603e-02,  2.49136500e-02, -1.07044410e-02, -6.40162453e-02,
        2.82347575e-02, -6.39095157e-02, -3.43310125e-02, -3.61878276e-02,
       -3.11370613e-03,  5.12572639e-02, -1.04132146e-01,  1.65327862e-02,
        1.87041424e-02,  8.78681093e-02, -9.71787423e-02, -5.44978753e-02,
       -2.86495630e-02,  6.52826428e-02, -1.60701666e-02, -2.90485527e-02,
        2.73743812e-02, -2.35411730e-02,  1.40439300e-02, -4.85140383e-02,
        6.63226023e-02, -6.48754463e-02,  7.22073019e-02,  3.07275690e-02,
        2.58168206e-02,  7.09933564e-02, -5.50338626e-02,  3.39141451e-02,
       -9.09138247e-02,  5.96926399e-02, -3.89810055e-02, -1.29547063e-02,
        2.24579545e-03, -1.72112975e-02,  2.45748926e-02,  1.91845689e-02,
        2.99281813e-02,  9.53115243e-03, -3.09056900e-02, -4.32515442e-02,
        1.12019263e-01,  2.41474546e-02,  2.44541001e-02,  6.59670960e-03,
       -1.95638724e-02,  

### Querying for Similarities (Dot Product)

This section demonstrates how to find sentences similar to a given query using the generated embeddings. The core idea is to measure the **similarity** between the query's embedding and the embeddings of our existing sentences:

1.  **Input Query**: `query = input("enter your query: ")` prompts you to type a question or statement.
2.  **Encode Query**: `query_vec = model.encode([query])` converts your input query into its own 384-dimensional embedding, just like we did with the initial sentences.
3.  **Calculate Similarity (Dot Product)**: `scores = np.dot(embeddings, query_vec.T)` calculates the **dot product** between each of our stored sentence embeddings and the query embedding. The dot product is a mathematical operation that, in the context of embeddings, measures how 'aligned' two vectors are. A higher dot product typically indicates greater semantic similarity.
    *   `embeddings`: Our collection of sentence embeddings (4x384 matrix).
    *   `query_vec.T`: The transpose of our query embedding (384x1 vector). Transposing makes the dimensions compatible for dot product calculation.
4.  **Print Scores**: `print(scores)` displays the similarity scores. Each score corresponds to one of our original sentences, indicating its similarity to your query. The higher the score, the more similar the sentence is to the query.

In [ ]:
query= input("enter your query: ")
query_vec=model.encode([query])
scores=np.dot(embeddings, query_vec.T)
print(scores)

# Example Query and Output for this section:
# Query 1: Machine learning is AI?
# Output:
# [[0.79642236]
#  [0.34920692]
#  [0.3049997 ]
#  [0.5580896 ]]
# Query 2:Deep learning uses nueral networks with many layers
# Output:
# [[0.35919687]
#  [1.        ]
#  [0.12331748]
#  [0.3024181 ]]
# Query 3:What is the capital of India?
# Output:
# [[ 0.09631449]
# [-0.0469831 ]
# [-0.00284372]
# [ 0.03079253]]

enter your query: What is the capital of India?
[[ 0.09631449]
 [-0.0469831 ]
 [-0.00284372]
 [ 0.03079253]]
